export const SITE = {
  name: 'Raafat.os',
  title: 'Mohammed Raafat — Front-End Engineer · React · TypeScript',
  description:
    'Front-End Engineer at Breadfast specializing in React.js, React Native, and TypeScript. Building scalable production web applications, dashboards, and Fintech systems. Available for freelance work worldwide.',
  url: 'https://raafat.dev',
  author: 'Mohammed Raafat',
  email: 'mohamedraafatqourany@gmail.com',
  location: 'Cairo, Egypt',
  jobTitle: 'Front-End Engineer',
  company: 'Breadfast',
  twitter: '@mohammedqourany',
  github: 'https://github.com/MohamedRaafatQourany',
  linkedin: 'https://www.linkedin.com/in/mohammedqourany',
  keywords: [
    'Mohammed Raafat',
    'Mohamed Raafat Qourany',
    'Front-End Engineer',
    'React Developer',
    'React Native Developer',
    'TypeScript',
    'Next.js',
    'Breadfast',
    'Cairo Egypt Developer',
    'Freelance Web Developer',
    'Upwork',
    'Fintech Front-End',
    'JavaScript Engineer',
  ],
} as const;
